FROM cloudflare/cloudflared:latest AS cloudflared

FROM alpine:3.20
RUN apk add --no-cache ca-certificates netcat-openbsd

COPY --from=cloudflared /usr/local/bin/cloudflared /usr/local/bin/cloudflared
ENTRYPOINT ["cloudflared", "--no-autoupdate"]
